# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Deploy

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version'
        required: true
        default: "X.Y.Z"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-package: 'jdk'
          java-version: '11'

      - name: Set version
        run: |
          mvn --no-transfer-progress --batch-mode versions:set -DnewVersion=${{ github.event.inputs.releaseVersion }}
          mvn --no-transfer-progress --batch-mode versions:commit

      - name: Install
        run: mvn --no-transfer-progress --batch-mode clean install

      - name: Get artifacts
        run: |
          mkdir push
          cp ./ArmShopBridge/target/*.jar ./push
          rm -f ./push/original-*.jar
          rm -f ./push/*-shaded.jar

      - name: Github release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.releaseVersion }}
          fail_on_unmatched_files: true
          files: push/*
